// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAch7H3qV2TkkXvtzq0X-O9hCRHU4yRWw',
    appId: '1:551771648041:web:8cc7814a472f743fec2c38',
    messagingSenderId: '551771648041',
    projectId: 'ecommerce-41619',
    authDomain: 'ecommerce-41619.firebaseapp.com',
    storageBucket: 'ecommerce-41619.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATLKBvY6ZDmqNFZaJIvV8igsjaxBGpuE0',
    appId: '1:551771648041:android:9b32053872a45b00ec2c38',
    messagingSenderId: '551771648041',
    projectId: 'ecommerce-41619',
    storageBucket: 'ecommerce-41619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAmHDaofWzA2hUGe2Oqp092MHgM5uEHvM',
    appId: '1:551771648041:ios:baf6bed2f57bb590ec2c38',
    messagingSenderId: '551771648041',
    projectId: 'ecommerce-41619',
    storageBucket: 'ecommerce-41619.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
